.TH PYRENAMER 1

.SH NAME
\fBpyRenamer\fP \- Mass file renamer

.SH SYNOPSIS
.B pyrenamer
.RI [options]
.RI "[" active_dir "]"

.SH DESCRIPTION
\fBpyrenamer\fR is an application for mass file renaming.
Files can be renamed using patterns, substitutions, inserting or deleting text, or even manually.
Image files can be also renamed using their EXIF tags and music files can be renamed using their internal metadata.

.SH OPTIONS
.TP
.B "-h, --help"
Show pyRenamer help and usage.
.TP
.BI "-r, --root "rootdir
Set root of the directory tree.
.TP
.B "-v, --version"
Show pyRenamer version and exit.

.SH BUGS
If you find a bug, please report it at https://github.com/JoseAntonioRodriguez/pyrenamer/issues.
